### ISSUE TITLE
window10 无法弹幕朗读

### ISSUE THREAD

**Issue by nanagagako** [liuxian496/iceborne#11]
![1830f405619410155ec29f878b267f9](https://github.com/liuxian496/iceborne/assets/76641224/200a31a2-af9d-4793-a937-2115260da857)

**Comment by liuxian496** [comment]
抱歉最近有点忙，今天才回复。使用blc云插件时。请不要使用『H5插件地址』，会有同源策略限制，无法语音播报。请按照如下步骤获取插件地址：
（1）点击『云插件后台：』后方的链接『打开 blc 管理后台』

（2）在『直播弹幕姬BLC』的主页面向下拖动滚动条，找到『插件URL』，复制后面的网址。

（3）将复制好的网址，粘贴到『插件地址：』后的文本框
如图所示：
![插件URL](https://github.com/liuxian496/iceborne/assets/20082670/3cb7240a-9099-4d56-85f8-df9e6ec8e12d)

**Comment by nanagagako** [comment]
好的好的，谢谢！
&nbsp;


clelo7
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月19日(星期天) 晚上6:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuxian496/iceborne] window10 无法弹幕朗读 (Issue #11)














 
抱歉最近有点忙，今天才回复。使用blc云插件时。请不要使用『H5插件地址』，会有同源策略限制，无法语音播报。请按照如下步骤获取插件地址：
 （1）点击『云插件后台：』后方的链接『打开 blc 管理后台』
 
（2）在『直播弹幕姬BLC』的主页面向下拖动滚动条，找到『插件URL』，复制后面的网址。
 
（3）将复制好的网址，粘贴到『插件地址：』后的文本框
 如图所示：
 URL.jpg (view on web)
 
—
直接回复此电子邮件、在 GitHub 上查看或取消订阅。
您之所以收到此邮件，是因为您是该主题的作者。消息ID ：< ***@***.*** &gt;
